# Canonical skill alias map.
# Keys are lowercased aliases (including abbreviations and misspellings).
# Values are the canonical display names.
#
# Lookup strategy:
#   1. Exact lowercase match (O(1) dict lookup).
#   2. rapidfuzz fuzzy fallback at threshold ≥ 80 against canonical values.

CANONICAL_SKILLS: dict[str, str] = {
    # ── Python ecosystem ──────────────────────────────────────────────────────
    "python":           "Python",
    "python3":          "Python",
    "py":               "Python",
    "django":           "Django",
    "flask":            "Flask",
    "fastapi":          "FastAPI",
    "sqlalchemy":       "SQLAlchemy",
    "pandas":           "Pandas",
    "numpy":            "NumPy",
    "scipy":            "SciPy",
    "matplotlib":       "Matplotlib",
    "seaborn":          "Seaborn",
    "pytorch":          "PyTorch",
    "tensorflow":       "TensorFlow",
    "tf":               "TensorFlow",
    "keras":            "Keras",
    "sklearn":          "scikit-learn",
    "scikit-learn":     "scikit-learn",
    "scikit learn":     "scikit-learn",
    "nltk":             "NLTK",
    "spacy":            "spaCy",
    "huggingface":      "HuggingFace Transformers",
    "transformers":     "HuggingFace Transformers",
    "streamlit":        "Streamlit",
    "pydantic":         "Pydantic",
    "celery":           "Celery",
    "pytest":           "pytest",
    "unittest":         "unittest",

    # ── JavaScript / TypeScript ecosystem ────────────────────────────────────
    "javascript":       "JavaScript",
    "js":               "JavaScript",
    "typescript":       "TypeScript",
    "ts":               "TypeScript",
    "react":            "React",
    "reactjs":          "React",
    "react.js":         "React",
    "next.js":          "Next.js",
    "nextjs":           "Next.js",
    "vue":              "Vue.js",
    "vue.js":           "Vue.js",
    "vuejs":            "Vue.js",
    "angular":          "Angular",
    "angularjs":        "AngularJS",
    "node":             "Node.js",
    "node.js":          "Node.js",
    "nodejs":           "Node.js",
    "express":          "Express.js",
    "express.js":       "Express.js",
    "redux":            "Redux",
    "graphql":          "GraphQL",
    "webpack":          "Webpack",
    "vite":             "Vite",
    "jest":             "Jest",
    "tailwind":         "Tailwind CSS",
    "tailwindcss":      "Tailwind CSS",

    # ── Java ecosystem ────────────────────────────────────────────────────────
    "java":             "Java",
    "spring":           "Spring Boot",
    "spring boot":      "Spring Boot",
    "springboot":       "Spring Boot",
    "maven":            "Maven",
    "gradle":           "Gradle",
    "hibernate":        "Hibernate",
    "junit":            "JUnit",
    "kotlin":           "Kotlin",

    # ── JVM / other languages ─────────────────────────────────────────────────
    "scala":            "Scala",
    "groovy":           "Groovy",

    # ── C / C++ / Systems ─────────────────────────────────────────────────────
    "c":                "C",
    "c++":              "C++",
    "cpp":              "C++",
    "c#":               "C#",
    "csharp":           "C#",
    "dotnet":           ".NET",
    ".net":             ".NET",
    "rust":             "Rust",
    "go":               "Go",
    "golang":           "Go",

    # ── Databases ─────────────────────────────────────────────────────────────
    "sql":              "SQL",
    "mysql":            "MySQL",
    "postgresql":       "PostgreSQL",
    "postgres":         "PostgreSQL",
    "psql":             "PostgreSQL",
    "sqlite":           "SQLite",
    "mssql":            "SQL Server",
    "sql server":       "SQL Server",
    "oracle":           "Oracle DB",
    "mongodb":          "MongoDB",
    "mongo":            "MongoDB",
    "redis":            "Redis",
    "elasticsearch":    "Elasticsearch",
    "cassandra":        "Cassandra",
    "dynamodb":         "DynamoDB",
    "firebase":         "Firebase",

    # ── Cloud & DevOps ────────────────────────────────────────────────────────
    "aws":              "AWS",
    "amazon web services": "AWS",
    "gcp":              "GCP",
    "google cloud":     "GCP",
    "azure":            "Azure",
    "docker":           "Docker",
    "kubernetes":       "Kubernetes",
    "k8s":              "Kubernetes",
    "terraform":        "Terraform",
    "ansible":          "Ansible",
    "jenkins":          "Jenkins",
    "github actions":   "GitHub Actions",
    "ci/cd":            "CI/CD",
    "cicd":             "CI/CD",
    "linux":            "Linux",
    "bash":             "Bash",
    "shell":            "Shell Scripting",
    "shell scripting":  "Shell Scripting",
    "nginx":            "Nginx",
    "prometheus":       "Prometheus",
    "grafana":          "Grafana",

    # ── Data Engineering ──────────────────────────────────────────────────────
    "spark":            "Apache Spark",
    "apache spark":     "Apache Spark",
    "kafka":            "Apache Kafka",
    "apache kafka":     "Apache Kafka",
    "airflow":          "Apache Airflow",
    "apache airflow":   "Apache Airflow",
    "hadoop":           "Hadoop",
    "hive":             "Hive",
    "snowflake":        "Snowflake",
    "dbt":              "dbt",

    # ── ML / AI ───────────────────────────────────────────────────────────────
    "machine learning": "Machine Learning",
    "ml":               "Machine Learning",
    "deep learning":    "Deep Learning",
    "dl":               "Deep Learning",
    "nlp":              "NLP",
    "natural language processing": "NLP",
    "computer vision":  "Computer Vision",
    "cv":               "Computer Vision",
    "llm":              "LLMs",
    "llms":             "LLMs",
    "generative ai":    "Generative AI",
    "gen ai":           "Generative AI",
    "langchain":        "LangChain",
    "rag":              "RAG",

    # ── Web / General ─────────────────────────────────────────────────────────
    "html":             "HTML",
    "html5":            "HTML",
    "css":              "CSS",
    "css3":             "CSS",
    "sass":             "Sass",
    "scss":             "Sass",
    "rest":             "REST APIs",
    "rest api":         "REST APIs",
    "restful":          "REST APIs",
    "api":              "REST APIs",
    "graphql":          "GraphQL",
    "websocket":        "WebSockets",
    "oauth":            "OAuth",
    "jwt":              "JWT",

    # ── Tools & Practices ─────────────────────────────────────────────────────
    "git":              "Git",
    "github":           "GitHub",
    "gitlab":           "GitLab",
    "bitbucket":        "Bitbucket",
    "jira":             "Jira",
    "confluence":       "Confluence",
    "postman":          "Postman",
    "agile":            "Agile",
    "scrum":            "Scrum",
    "tdd":              "TDD",

    # ── Security ──────────────────────────────────────────────────────────────
    "cybersecurity":    "Cybersecurity",
    "cyber security":   "Cybersecurity",
    "penetration testing": "Penetration Testing",
    "pen testing":      "Penetration Testing",
    "owasp":            "OWASP",

    # ── Mobile ────────────────────────────────────────────────────────────────
    "android":          "Android",
    "ios":              "iOS",
    "swift":            "Swift",
    "flutter":          "Flutter",
    "react native":     "React Native",
}